name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag cbr-api:latest
          echo "${{ github.repository_owner }}/${{ github.event.repository.name }}:latest" > IMAGE_NAME

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push image to GitHub Container Registry
        run: |
          docker tag cbr-api:latest ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
